const Common = {
    url_api: "http://127.0.0.1:5000/api/customers",
    id: "ID",
    full_name: "Nombre completo",
    phone: "Telefono",
    email: "Correo Electronico",
    age: "Edad",
    state: "Estado",
    created_at: "Fecha de creación",
    actions: "Acciones",
    load: "Cargando...",
    edit: "Editar",
    delete: "Borrar",
    customer: "Cliente",
    add: "Agregar",
    cancel: "Cancelar",
    name: "Nombre(s)",
    surnames: "Apellido(s)",
    send: "Enviar",
    new: "Nuevo",
    not_interested: "No interesado",
    wrong_number: "Número equivocado",
    wrong_information: "Información equivocado",
    high_potential: "Alto potencial",
    low_potential: "Bajo potencial",    
};
export default Common;